hydra:
  run:
    dir: ./outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}-${task.name}-${algo.name}
  job:
    chdir: true

headless: true
exp_name: ${oc.select:task.name,test}-${oc.select:algo.name,none}

backend: isaac
device: cuda

app:
  headless: ${..headless}
  enable_cameras: ${..eval_render}

# total_frames: 300_000_000
total_frames: 150_000_000
max_iters: -1
eval_interval: -1
eval_render: false
checkpoint_interval: 4
upload_interval: 100
render_interval: -1
render_decimation: 4
seed: 42
checkpoint_path: null
discard_unused_obs: true

camera_follow: true

wandb:
  name: ${..exp_name}/${now:%m-%d}_${now:%H-%M}
  job_type: train
  project: ${oc.select:task.project,active_adaptation}
  mode: online # set to 'disabled' when debugging locally
  tags: []

defaults:
  - task: Velocity
  - algo: ppo
  - _self_
