# @package task
name: A2LocoManipObject

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: unitree_a2_piper
objects:
  object:
    _target_: dummy_stand
terrain: plane


# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.005
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: ConcatenatedAction
    actions:
      - _target_: JointPosition
        action_scaling:
          .*_hip_joint: 0.4
          .*_thigh_joint: 0.4
          .*_calf_joint: 0.4
          arm_joint[4-6]: 0.35
        max_delay: 1
        alpha_range: [0.8, 0.9]
      - _target_: CorrelatedJointPosition
        joint_names: "arm_joint[7,8]"
        # arm_joint7: [0, 0.035], arm_joint8: [-0.035, 0] -> open/close together
        matrix: [1.0, -1.0]
        action_scaling: 0.035
      - _target_: JointPositionDelta
        action_scaling:
          arm_joint[1-3]: 0.4
        max_delay: 1
        alpha_range: [0.8, 0.9]

command:
  _target_: LocoManipObject
  eef_body_name: grasp_point
  gripper_joint_names: "arm_joint[7,8]"
  gripper_body_names: [gripper_left, gripper_right]
  object_name: object
  target_offset_range: [-2.0, 2.0]
  object_vel_gain: 1.0
  object_vel_limit: 0.5
  grasp_height_range: [0.3, 0.6]

observation:
  command:
    command:  {key: "object"}
  policy:
    gravity_multistep: {steps: 4, noise_std: 0.05}
    joint_pos_multistep: {steps: 4, noise_std: 0.05}
    joint_vel_multistep: {steps: 4, noise_std: 0.2}
    prev_actions: {steps: 2}
  # priv:
    body_vel_b: {body_names: grasp_point}
    root_linvel_b:    {yaw_only: true}
    root_angvel_b:    {}
  extero:
    height_scan: {
      x_range: [-1.2, 1.2],
      y_range: [-1.0, 1.0],
      resolution: [0.1, 0.1],
      flatten: false,
    }

reward:
  loco:
    angvel_xy_l2:       {weight: 0.01}
    linvel_z_l2:        {weight: 2.0}
    base_height_exp:    {weight: 1.0, target_height: 0.4, sigma: 0.4}
  manip_object:
    object_pos_tracking: {weight: 1.0}
    object_vel_tracking: {weight: 1.0}
  manip_eef:
    object_grasp_pos:   {weight: 1.0, grasp_sigma: 0.25}
    # eef_grasp:          {weight: 1.0}
    eef_angvel_penalty: {weight: 0.005}
  regularization:
    energy_l1:          {weight: 0.0005}
    joint_acc_l2:       {weight: 2.5e-7, joint_names: "(?!(arm_joint[7,8])).*" } # exclude gripper joints
    joint_torques_l2:   {weight: 1.0e-4, joint_names: "(?!(arm_joint[7,8])).*" } # exclude gripper joints
    survival:           {weight: 1.0}
    action_rate_l2:     {weight: 0.01}
    action_rate2_l2:    {weight: 0.002}
    feet_air_time:      {weight: 0.4, body_names: .*_foot, thres: 0.5}
    feet_sliding:       {weight: 0.2, body_names: .*_foot}
    undesired_contact:  {body_names: [.*_calf, .*thigh], weight: 0.25}
  debug:
    _enabled_: false
    feet_contact_count: {weight: 1.0, body_names: .*_foot}

termination:
  max_episode_length: {}
  crash: {body_names_expr: [base_link, .*hip, .*thigh], t_thres: 0.06}
  robot_fall_over: {
    _target_: fall_over,
    entity_name: robot,
    xy_thres: 0.9,
  }
  object_fall_over: {
    _target_: fall_over,
    entity_name: object,
    xy_thres: 0.9,
  }
  undesired_contact: {body_names: [.*_calf]}

randomization:
  perturb_body_mass:
    .*: [0.8, 1.2]
  perturb_body_materials:
    body_names: .*_foot
    static_friction_range:  [0.5, 3.0]
    dynamic_friction_range: [0.5, 3.0]
    restitution_range:      [0.0, 0.5]
  actuator_pd_gains:
    stiffness_range:
      .*: [0.8, 1.1]
    damping_range:
      .*: [0.8, 1.1]
  reset_joint_states_scale:
    pos_scales:
      .*: [0.8, 1.2]
