# @package task
name: B1Z1Force

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [0.0, 4.0, 3.0]

robot: 
  name: b1z1
terrain: plane

# common
num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.004
  mujoco_physics_dt: 0.002

action:
  _target_: active_adaptation.envs.mdp.action.JointPosition
  action_scaling:
    (F|R)(L|R)_(thigh|calf)_joint: 0.5
    (F|R)(L|R)_hip_joint: 0.5
    arm_joint[1-5]: 1.0
  alpha_range: [0.75, 0.95]
  max_delay: 1

command:
  _target_: ImpedanceCommandManager
  virtual_mass_range: [2., 4., 6.]
  eef_body_name: gripperMover
  arm_body_name: arm_link1
  ref_steps: [8, 16, 32]
  temporal_smoothing: 32

observation:
  policy:
    command:
    gravity_multistep:  {steps: 4, noise_std: 0.05}
    joint_pos_multistep: {steps: 4, noise_std: 0.05}
    joint_vel_multistep: {steps: 4, noise_std: 0.2}
    prev_actions: {steps: 3}
    body_pos_b:       {body_names: "gripperMover", yaw_only: true}
  # priv:
    command_hidden:
    root_linvel_b:    {yaw_only: true}
    root_angvel_b:
    contact_indicator: {body_names: [".*_foot"]}
    body_vel_b:       {body_names: "gripperMover", yaw_only: true}
  ext:
    external_forces:  {body_names: ["base", "gripperMover"]}
    external_torques: {body_names: ["base"]}
  ext_:
    external_forces:  {body_names: ["base", "gripperMover"]}
    external_torques: {body_names: ["base"]}

reward:
  loco:
    # common loco rewards just for sanity check
    impedance_yaw_pos:      {weight: 0.75}
    impedance_yaw_vel:      {weight: 1.0}
    impedance_pos:      {weight: 0.75}
    impedance_vel:      {weight: 1.5}
    base_height_exp:    {weight: 2.0, target_height: 0.5}
  arm:
    impedance_eef_pos:      {weight: 1.0}
    impedance_eef_vel:      {weight: 1.0}
    # ee_angvel_penalty:    {weight: 0.01}
    joint_vel_l2:       {weight: 0.002, joint_names: .*arm_joint.*}
  regularization:
    angvel_xy_l2:       {weight: 0.01}
    linvel_z_l2:        {weight: 2.0}
    energy_l1:          {weight: 0.0002}
    joint_acc_l2:       {weight: 1.0e-7}
    joint_torques_l2:   {weight: 2.0e-5}
    survival:           {weight: 2.0}
    action_rate_l2:     {weight: 0.005}
    action_rate2_l2:    {weight: 0.005}
    feet_air_time:      {weight: 0.5, body_names: .*_foot, thres: 0.3}
    # feet_slip:          {weight: 0.5, body_names: .*_foot}
    undesired_contact:  {body_names: [.*_calf, .*thigh], weight: 1.0}
  metrics:
    _enabled_: false
    # impedance_acc_error: {weight: 1.0} # not implemented
    impedance_vel_error: {weight: 1.0}
    impedance_pos_error: {weight: 1.0}

termination:
  crash: {body_names_expr: ["base", ".*calf.*", "arm_link[1-6]"], t_thres: 0.05}
  fall_over: {xy_thres: 0.9}

randomization:
  perturb_body_mass:
    (?!(payload|base.*)).*: [0.8, 1.1]
    base: [0.8, 1.1]
  perturb_body_materials:
    body_names: ".*_foot"
    static_friction_range:  [0.6, 4.0]
    dynamic_friction_range: [0.6, 4.0]
    restitution_range:      [0.0, 0.2]
    homogeneous: true # ${task.homogeneous}
  # actuator_pd_gains:
  #   actuator_name: base_arm
  #   stiffness_range:  [0.8, 1.2]
  #   damping_range:    [0.8, 1.2]
  #   armature_range:   [0.0, 0.02]
  #   homogeneous: ${task.homogeneous}
  # reset_joint_states_uniform:
  #   pos_ranges:
  #     .*_thigh_joint: [-0.2, 0.2]
  #     .*_calf_joint: [-0.2, 0.2]
  #     .*_hip_joint: [-0.2, 0.2]
  #   rel: true
  # stumble: {body_names: .*_foot, stumble_height: 0.02, friction_range: [0.2, 0.4]}
