# @package task
name: BlueROVHeavy
project: underwater

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: bluerov_heavy

terrain: plane

num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.01
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: UnderwaterThrottle

command:
  _target_: TrajTracking
  target_range: [[-4.0, 4.0], [-4.0, 4.0], [-1.0, 1.0]]
  future_steps: [1, 4]
  vel_range: [[-1.0, 1.0], [-1.0, 1.0], [0.0, 0.0]]
  duration_range: [10.0, 20.0]
  look_at_goal_prob: 0.5
  resample_interval: 200
  resample_prob: 0.2

observation:
  command:
    command: {}
  policy:
    root_linvel_b: {yaw_only: true}
    root_angvel_b: {}
    gravity_multistep: {steps: 4, noise_std: 0.05}
    # underwater.baro_pressure: {body_name: base_link}
    # underwater.dvl_linvel:    {body_name: base_link}
  extero:
    underwater.uw_camera:
      body_name: base_link
      clipping_range: [0.2, 10.0]
      offset_pos: [0.1, 0.0, 0.0]
      debug_vis: true

reward:
  navi:
    position_tracking: {weight: 1.5, sigma: 0.25}
    velocity_tracking: {weight: 1.0, sigma: 0.25}
    orientation_tracking: {weight: 1.0, sigma: 0.5}
    survival: {weight: 1.0}

termination:
  max_episode_length: {}
  position_error_exceeding: {threshold: 1.0}
