# @package task
name: BlueROVHeavy

viewer:
  resolution: [1280, 720]
  lookat: [0., 0., 0.]
  eye: [4.0, 4.0, 4.0]

robot:
  name: bluerov_heavy

terrain: plane

num_envs: 4096
max_episode_length: 1000

sim:
  step_dt: 0.02
  isaac_physics_dt: 0.01
  mujoco_physics_dt: 0.002

input:
  action:
    _target_: UnderwaterThrottle

command:
  _target_: Twist
  linvel_x_range: [-1.0, 1.6]
  linvel_y_range: [-0.8, 0.8]
  angvel_range:   [-2.0, 2.0]
  yaw_stiffness_range: [0.5, 1.1]
  use_stiffness_ratio: 0.99
  resample_prob: 0.5
  stand_prob: 0.08

observation:
  policy:
    command:  {}
    gravity_multistep: {steps: 4, noise_std: 0.05}
    underwater.baro_pressure: {body_name: base_link}
    underwater.dvl_linvel:    {body_name: base_link}

reward:
  navi:
    survival: {weight: 1.0}

termination:
  max_episode_length: {}
