# @package _global_
name: b2_teacher_student
work_dir: ./outputs_pipeline/${name}/${now:%Y-%m-%d-%H-%M-%S}

stages:
  - name: b2_teacher
    script: train_ppo.py
    overrides:
      - task=B2/B2LocoDreamWaQ
      - task.num_envs=8192
      - algo=ppo_teacher
      - algo.teacher_keys=[policy,priv]
      - algo.student_keys=[policy]
      - total_frames=100_000_000
      - backend=isaac
      - eval=False

  - name: b2_student1
    script: train_ppo.py
    overrides:
      - task=B2/B2LocoDreamWaQ
      - task.num_envs=8192
      - algo=ppo_student1
      - algo.teacher_keys=[policy,priv]
      - algo.student_keys=[policy]
      - total_frames=50_000_000
      - backend=isaac
      - eval=False
      - checkpoint_path=${run_state.checkpoint_path}

  - name: b2_student2
    script: train_ppo.py
    overrides:
      - task=B2/B2LocoDreamWaQ
      - task.num_envs=8192
      - algo=ppo_student2
      - algo.teacher_keys=[policy,priv]
      - algo.student_keys=[policy]
      - total_frames=50_000_000
      - backend=isaac
      - eval=True
      - checkpoint_path=${run_state.checkpoint_path}
